language: java
jdk:
 - oraclejdk8
dist: trusty
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notifications:
  email:
    recipients:
      - junior7395@hotmail.es
      - jescoevas@alum.us.es
      - danibenitez012@gmail.com
      - jesescagu@alum.us.es
    on_success: never # default: change
    on_failure: always # default: always
